services:

  bot:
    build: 
      dockerfile: docker/bot/Dockerfile
    container_name: jamming-bot
    restart: unless-stopped
    ports:
      - "7001:7001"
    env_file:
      - .env      
    volumes:
      - type: bind
        source: ./app/bot
        target: /app
      - type: bind
        source: ./data
        target: /app/data 
    depends_on:
      - redis  
    networks:
      - app_network         

  redis: 
    image: redislabs/redismod
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    networks:
      - app_network

  flask:
    build: 
      dockerfile: docker/flask/Dockerfile
    image: master-image
    container_name: flask
    restart: unless-stopped
    ports:
      - "5000:5000"
    command: python app.py
    env_file:
      - .env    
    volumes:
      - type: bind
        source: ./app/flask
        target: /app
      - type: bind
        source: ./data
        target: /app/data 
    depends_on:
      - redis
    networks:
      - app_network


  tags_service:
    build: ./tags-service
    container_name: tags_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./tags-service/:/app/
    ports:
      - 8003:8000
    environment:
      - DATABASE_URI=postgresql://tags_db_username:tags_db_password@tags_db/tags_db_dev
      - CAST_SERVICE_HOST_URL=http://tags_service:8000/api/v1/casts/
    networks:
      - app_network
    depends_on:
      - tags_db

  tags_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_tags:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tags_db_username
      - POSTGRES_PASSWORD=tags_db_password
      - POSTGRES_DB=tags_db_dev
    networks:
      - app_network

  worker:    
    build: 
      dockerfile: docker/worker/Dockerfile
    image: worker-image
    command: rq worker --name worker --disable-job-desc-logging --url redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./app/flask
        target: /app
      - type: bind
        source: ./data
        target: /app/data 
    depends_on:
      - redis
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.25'

  #uncomment to have a another worker
  worker2:
    image: worker-image
    command: rq worker --name worker2 --disable-job-desc-logging --url redis://redis:6379/0
    volumes:
      - type: bind
        source: ./app/flask
        target: /app
      - type: bind
        source: ./data
        target: /app/data    
    depends_on:
      - redis
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.25'  



  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app_network


  dashboard:
    image: master-image
    ports:
      - 5555:5555
    depends_on:
      - redis
    command: rq-dashboard --port 5555 --redis-url redis://redis:6379/0 
    networks:
      - app_network


volumes:
  postgres_data_tags:
  data:
    external: true
  app:
  app-ip:

networks:
  app_network:
    driver: bridge