services:

  bot:
    build: 
      dockerfile: docker/bot/Dockerfile
    container_name: jamming-bot
    restart: unless-stopped
    ports:
      - "7001:7001"
    env_file:
      - .env      
    volumes:
      - type: bind
        source: ./app/bot
        target: /app
      - type: bind
        source: ./data
        target: /app/data 
    depends_on:
      - redis  
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.5'


  redis: 
    image: redislabs/redismod
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    networks:
      - app_network


  flask:
    build: 
      dockerfile: docker/flask/Dockerfile
    image: master-image
    container_name: flask
    restart: unless-stopped
    ports:
      - "5000:5000"
    command: python app.py
    env_file:
      - .env    
    volumes:
      - type: bind
        source: ./app/flask
        target: /app
      - type: bind
        source: ./data
        target: /app/data 
    depends_on:
      - redis
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.5'

  # adapter:
  #   build: 
  #     dockerfile: docker/adapter/Dockerfile
  #   container_name: adapter
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - type: bind
  #       source: ./adapter
  #       target: /app
  #   depends_on:
  #     - flask
  #   networks:
  #     - app_network    

  # worker:    
  #   build: 
  #     dockerfile: docker/worker/Dockerfile
  #   image: worker-image
  #   command: rq worker --name worker --disable-job-desc-logging --url redis://redis:6379/0
  #   env_file:
  #     - .env
  #   volumes:
  #     - type: bind
  #       source: ./app/flask
  #       target: /app
  #     - type: bind
  #       source: ./data
  #       target: /app/data 
  #   depends_on:
  #     - redis
  #   networks:
  #     - app_network

  # uncomment to have a another worker
  # worker2:
  #   image: worker-image
  #   command: rq worker --name worker2 --url redis://redis:6379/0
  #   volumes:
  #     - type: bind
  #       source: ./app/flask
  #       target: /app
  #     - type: bind
  #       source: ./data
  #       target: /app/data    
  #   depends_on:
  #     - redis  

  # dashboard:
  #   image: master-image
  #   ports:
  #     - 5555:5555
  #   depends_on:
  #     - redis
  #   command: rq-dashboard --port 5555 --redis-url redis://redis:6379/0  

  
  spacyapi:
    container_name: spacyapi
    image: bbieniek/spacyapi:en_v3
    ports:
      - "127.0.0.1:7010:80"
    restart: always
    networks:
      - app_network

  # screenshoter:
  #   image: mingalevme/screenshoter
  #   ports:
  #     - "5020:8080"
  #   restart: always
  #   networks:
  #     - app_network      



  ip_service:
    build: ./ip-service
    container_name: ip_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8004
    volumes:
      - ./ip-service/:/app/
      - type: bind
        source: ./ip-service/data
        target: /app/data
    ports:
      - 8004:8004
    environment:
      - DATABASE_URI=postgresql://tags_db_username:tags_db_password@tags_db/tags_db_dev
    networks:
      - app_network

  semantic_service:
    build: ./semantic-service
    container_name: semantic_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8005
    restart: unless-stopped
    volumes:
      - ./semantic-service/:/app/
      - type: bind
        source: ./semantic-service/data
        target: /app/data
    ports:
      - 8005:8005
    environment:
      - DATABASE_URI=postgresql://tags_db_username:tags_db_password@tags_db/tags_db_dev
    networks:
      - app_network
    depends_on:
      - tags_db


  tags_service:
    build: ./tags-service
    restart: unless-stopped
    container_name: tags_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./tags-service/:/app/
    ports:
      - 8003:8000
    environment:
      - DATABASE_URI=postgresql://tags_db_username:tags_db_password@tags_db/tags_db_dev
      - CAST_SERVICE_HOST_URL=http://tags_service:8000/api/v1/casts/
    networks:
      - app_network
    depends_on:
      - tags_db


  keywords_service:
    build: ./keywords-service
    restart: unless-stopped
    container_name: keywords_service
    ports:
      - "7771:7771"
    volumes:
      - ./keywords-service/:/usr/src/app
    networks:
      - app_network


  tags_db:
    image: postgres:12.1-alpine
    restart: unless-stopped
    volumes:
      - postgres_data_tags:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tags_db_username
      - POSTGRES_PASSWORD=tags_db_password
      - POSTGRES_DB=tags_db_dev
    networks:
      - app_network

  worker:    
    build: 
      dockerfile: docker/worker/Dockerfile
    image: worker-image
    command: rq worker --name worker --disable-job-desc-logging --url redis://redis:6379/0
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./app/flask
        target: /app
      - type: bind
        source: ./data
        target: /app/data 
    depends_on:
      - redis
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.25'

  #uncomment to have a another worker
  worker2:
    image: worker-image
    command: rq worker --name worker2 --disable-job-desc-logging --url redis://redis:6379/0
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./app/flask
        target: /app
      - type: bind
        source: ./data
        target: /app/data    
    depends_on:
      - redis
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.25'  

  rq-dashboard:
    image: kudaw/rq-dashboard
    restart: unless-stopped
    environment:
      RQ_DASHBOARD_REDIS_URL: 'redis://redis:6379'
    ports:
      - "9181:9181"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - redis
    networks:
      - app_network

  nginx:
    container_name: nginx
    restart: "no"
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "5001:5001"
    volumes:
      - type: bind
        source: ./data/certbot/www
        target: /var/www/certbot
      - type: bind
        source: ./frontend/build
        target: /var/www
    depends_on:
      - flask
      - redis
      - tags_service
    networks:
      - app_network 


  certbot:
    image: certbot/certbot:latest
    volumes:
      - type: bind
        source: ./data/certbot/www
        target: /var/www/certbot
      - type: bind
        source: ./data/certbot/www
        target: /etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --non-interactive --email alexey.roudenko@gmail.com --agree-tos --preferred-challenges http -d jamming-bot.arthew0.online      

  certbotn8n:
    image: certbot/certbot:latest
    volumes:
      - type: bind
        source: ./data/certbot/www
        target: /var/www/certbot
      - type: bind
        source: ./data/certbot/www
        target: /etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --non-interactive --email alexey.roudenko@gmail.com --agree-tos --preferred-challenges http -d n8n.arthew0.online 

volumes:
  postgres_data_tags:
  data:
    external: true
  app:
  app-ip:

networks:
  app_network:
    driver: bridge