version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7781:7781"
    volumes:
      - ./src:/usr/src/app
    environment:
      NODE_ENV: development

networks:
  default:
    driver: bridge